import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // We'll create a single sidebar for the whole docs site
  docsSidebar: [
    
    // --- 1. The Main "Control Room" Section ---
    {
      type: 'category',
      label: 'Control Room',
      collapsible: false, // Keep this open by default
      link: {
        type: 'doc',
        id: 'control-room/control-room-index', // <-- CORRECTED
      },
      items: [
        'control-room/control-room-quickstart', // <-- CORRECTED
      ],
    },

    // --- 2. A Heading for Products ---
    {
      type: 'html',
      value: 'Products',
      className: 'sidebar-divider', // You can style this in src/css/custom.css
    },

    // --- 3. Dispatch Product ---
    {
      type: 'category',
      label: 'Dispatch',
      link: {
        type: 'doc',
        id: 'dispatch/dispatch-index', // <-- CORRECTED
      },
      items: [
        'dispatch/dispatch-getting-started', // <-- CORRECTED
        'dispatch/dispatch-reference', // <-- CORRECTED
      ],
    },

    // --- 4. Flight Recorder Product ---
    {
      type: 'category',
      label: 'Flight Recorder',
      link: {
        type: 'doc',
        id: 'flight-recorder/flight-recorder-index', // <-- CORRECTED
      },
      items: [
        // As you add files like 'flight-recorder/setup.md', add them here
      ],
    },

    // --- 5. Pipe Audit Product (with sub-sections) ---
    {
      type: 'category',
      label: 'Pipe Audit',
      link: {
        type: 'doc',
        id: 'pipe-audit/pipe-audit-index', // <-- CORRECTED
      },
      items: [
        {
          type: 'category',
          label: 'CLI',
          link: { type: 'doc', id: 'pipe-audit/cli/cli-index' }, // <-- CORRECTED
          items: [
            {
              type: 'autogenerated',
              dirName: 'pipe-audit/cli', 
            },
          ],
        },
        {
          type: 'category',
          label: 'Core Library',
          link: { type: 'doc', id: 'pipe-audit/core/core-index' }, // <-- CORRECTED
          items: [
            {
              type: 'autogenerated',
              dirName: 'pipe-audit/core', 
            },
          ],
        },
        {
          type: 'category',
          label: 'Contributing',
          link: { type: 'doc', id: 'pipe-audit/contributing/contributing-index' }, // <-- CORRECTED
          items: [
            {
              type: 'autogenerated',
              dirName: 'pipe-audit/contributing', 
            },
          ],
        },
      ],
    },

    // --- 6. Future Products (Placeholders) ---
    {
      type: 'category',
      label: 'Gatehouse',
      link: {
        type: 'doc',
        id: 'gatehouse/gatehouse-index', // <-- CORRECTED
      },
      items: [],
    },
    {
      type: 'category',
      label: 'Redeliver',
      link: {
        type: 'doc',
        id: 'redeliver/redeliver-index', // <-- CORRECTED
      },
      items: [],
    },
    {
      type: 'category',
      label: 'Foreman',
      link: {
        type: 'doc',
        id: 'foreman/foreman-index', // <-- CORRECTED
      },
      items: [],
    },
    {
      type: 'category',
      label: 'Tracks',
      link: {
        type: 'doc',
        id: 'tracks/tracks-index', // <-- CORRECTED
      },
      items: [],
    },
  ],
};

export default sidebars;